#!/bin/sh

set -e

# BUILD_NUMBER should be set

./gradlew publishMavenJavaPublicationToLocalFilesRepository

tmpdir=$(TMPDIR=build mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

for pom in $(find build/repo -name "*.$BUILD_NUMBER.pom"); do
    pomdir=$(dirname "$pom")
    basename=$(basename "$pom" .pom)
    bundlefilename="$basename-bundle.jar"
    for file in "$basename.pom" "$basename.jar" "$basename-javadoc.jar" "$basename-sources.jar"; do
	if [ -f "$pomdir/$file" ]; then
	    ln "$pomdir/$file" "$tmpdir"
	    gpg -ab "$tmpdir/$file"
	fi
    done
    
    files=$( cd "$tmpdir" && echo *.jar *.pom *.jar.asc *.pom.asc )

    args=$( for file in $files; do echo -C "$tmpdir" $file; done )

    jar -cvf build/"$bundlefilename" $args
done
