name: "Gradle Build"
on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
